# Generated by Django 4.0.6 on 2022-09-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locaion',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
